import Locker from '#models/locker'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    // Write your database queries inside the run method

    const lockers = [
      { lockerNumber: 'B001', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B002', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B003', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B004', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B005', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B006', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B007', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B008', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B009', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B010', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B011', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B012', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B013', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B014', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B015', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B016', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B017', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B018', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B019', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B020', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B021', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B022', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B023', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B024', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B025', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B026', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B027', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B028', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B029', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B030', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B031', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B032', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B033', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B034', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B035', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B036', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B037', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B038', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B039', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B040', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B041', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B042', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B043', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B044', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B045', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B046', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B047', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B048', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B049', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B050', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B051', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B052', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B053', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B054', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B055', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B056', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B057', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B058', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B059', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B060', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B061', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B062', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B063', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B064', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B065', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B066', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B067', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B068', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B069', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B070', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B071', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B072', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B073', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B074', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B075', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B076', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B077', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B078', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B079', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B080', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B081', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B082', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B083', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B084', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B085', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B086', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B087', roomName: 'B05', site: 'Vennes' },
      { lockerNumber: 'B088', roomName: 'B05', site: 'Vennes' },
    ]

    await Locker.createMany(lockers)
  }
}
